### ISSUE TITLE
The YouTube icon on tab disappears when audio is playing under compact density

### ISSUE THREAD

**Issue by Liopleus** [edo0/Technetium#1]
When I play a video on YouTube under the compact density, the website icon disappears and only the "audio playing" icon is present.

This problem doesn't occur under the standard density.

![image](https://user-images.githubusercontent.com/85976467/122150309-0803a080-ce90-11eb-9281-6ada5b7e996f.png)

**Comment by edo0** [comment]
Thank you very much for pointing that out!
Closing the bug report, as now it should be working alright
