### ISSUE TITLE
Force open text as search term instead of url on new tab page

### ISSUE THREAD

**Issue by nettnikl** [edo0/Technetium#3]
Hi! Thanks for your efforts to make the newest firefix version practical again.
I'm not sure wheter this is doable or even in the scope of this project. However, maybe you have a hint for me.
The latest Firefox update impacted my workflow heavily, as the new 'new tab' page does not offer a 'search the web' bar anymore, and instead redirects my queries to the url bar. This in turn interprets my query as an url, or application link, if it fits. For example "NullPointerException: caused by x", as it interprets it as link to an application, instead of searching the web for the text.
Is there a way to modify the new firefox ui to restore my workflow? (ctrl t, ctrl v, enter, voilà the search results)

**Comment by edo0** [comment]
Thank you for trusting me with such a thorny issue.
It's been a while I have been reading complaints on Reddit communities about Firefox's handling of new tabs.
I am not knowledgeable enough to help you out on this, but I think you should bring up your specific situation in either of these communities
[https://www.reddit.com/r/FirefoxCSS/](https://www.reddit.com/r/FirefoxCSS/)
[https://www.reddit.com/r/startpages/](https://www.reddit.com/r/startpages/)

Especially in the latter community, I recall seeing some months ago heated conversations on how to possibly "steal back" focus from the new tab navbar, to a custom search bar within the new tab [setting new tabs to open custom startpages, with user-defined search bar - which could possibly be a workaround for your issue]
I haven't checked back recently, but I hope you'll find more experienced UX tweakers who will be able to help you out!!
