### ISSUE TITLE
Minimum tab width destroyed after installing Technetium

### ISSUE THREAD

**Issue by ghost** [edo0/Technetium#4]
The minimum tab width before horizontal scrolling occurs was permanantly reduced in my profile after installing Technetium. It now looks like chromium when with many tabs open, that is to say the tab titles are obscured. This persists even after the chrome directory and user.js are removed.
![image](https://user-images.githubusercontent.com/70460004/124535025-fc5b2800-de04-11eb-82ed-6e6caa5dff45.png)

**Comment by ghost** [comment]
I figured it out, its the line in the user.js:
`user_pref("browser.tabs.tabMinWidth", 0);`

**Comment by edo0** [comment]
Hi! Yes, that is correct. I had t recur to that gimmick in order to ensure that the "close" button is always displayed on tabs.
If you were aware of any way to achieve this, I would consider reinstating the correct values for `tabMinWidth`
