### ISSUE TITLE
Icons 

### ISSUE THREAD

**Issue by recoed** [edo0/Technetium#5]
Icons don´t displaying correctly when you right click on a tab

**Comment by edo0** [comment]
Thank you for the bug report!
Could you tell me what OS and Firefox version you are using?

**Comment by recoed** [comment]
Windows 10 and firefox 89.0.2

**Comment by edo0** [comment]
Sorry for being late in getting back to you, real like commitments held me back.
Could you please try the latest release (v.2.1.0) and tell me if that fixes your issue?

**Comment by recoed** [comment]
Yeah!!! It´s working fine now. Thank you for this. :)

**Comment by edo0** [comment]
Thank you very much for bringing the issue to my attention :)
