### ISSUE TITLE
Tabs are no longer compact as of v2.1.0

### ISSUE THREAD

**Issue by reicordine** [edo0/Technetium#6]
While v2.1.0 has fixed the issue I had with the context menu having broken formatting (thanks!), the tabs are no longer compact even with compact density enabled; they are instead the size of the normal density tabs of Proton. 

v1.1.2 does not have this issue. I don't think that v2.0.0 had this issue either.

**Comment by edo0** [comment]
Thank you very much for the bug report! I do not currently have a Windows computer to test this, could you please upload a screenshot/gif of what what the bug manifests like?

**Comment by reicordine** [comment]
Sure thing. Here's an image comparing the tabs of v1.1.2 to v2.1.0 (some poor cropping on my part, sorry):

![compact-technetium](https://user-images.githubusercontent.com/42733747/125632267-967b2dd2-3b62-49df-b5b9-1e0d33a88729.png)

As you can see, the tabs are much taller now.

**Comment by edo0** [comment]
Thank you very much, tonight I will have a look into it and will get back to you

**Comment by edo0** [comment]
Could you please try using this userChrome and tell me if it fixes your issue?
[userChrome.css.zip](https://github.com/edo0/Technetium/files/6818416/userChrome.css.zip)

**Comment by reicordine** [comment]
Unfortunately I still have the issue when replacing the old userChrome.css with your new file.

**Comment by edo0** [comment]
Could you please confirm whether also 2.0.0 yielded such an abnormal behaviour, or was introduced specifically with 2.1.0?

**Comment by reicordine** [comment]
I can confirm that the tabs are still compact as expected in v2.0.0.

**Comment by edo0** [comment]
Thank you for your feedback
New attempt, else it may have something to do with upstream (Lepton), and I will report this issue to its dev as well
[userChrome.css.zip](https://github.com/edo0/Technetium/files/6818806/userChrome.css.zip)

PS: sorry to make this more labour intensive for you, unfortunately this behaviour is completely non-reproducible on Linux

**Comment by reicordine** [comment]
Sorry for the delay in testing out the new userChrome. Unfortunately I'm still having the issue when trying the new userChrome.

I don't mind testing this for you, it's no problem.

**Comment by edo0** [comment]
I have tried version 2.1.1, just released, on a Windows 7 machine without issues (FF 90).
Could you please try this latest version on a friend or family member's Firefox / a clean nightly install, to make sure Technetium is to blame - and that no other configuration may be interfering?

**Comment by reicordine** [comment]
Hey, I've just tried the 2.1.1 release on this same Windows 10 device (I have no other devices) and I can confirm that you have solved the issue and tabs are now compact as they should be. Thanks and great job!

**Comment by edo0** [comment]
Great to know!! Thank you for assisting me in testing this!
